image: node:latest

stages:
  - test
  - staging
  - production

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

testing_deploy:
  stage: test
  only:
    - master
  script:
    - npm install
    - wget http://ipinfo.io/ip -qO - && nproc

deploy_to_staging:
  stage: staging
  only:
    - master
  script:
    - wget http://ipinfo.io/ip -qO - && nproc
    - npm install -g firebase-tools
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN

deploy_to_production:
  stage: production
  script:
    - npm install
    - npm install -g firebase-tools
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN

  only:
    - tags
