---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - wget http://ipinfo.io/ip -qO - && nproc
  - wget http://ipinfo.io/ip -qO - && nproc
  - wget http://ipinfo.io/ip -qO - && nproc

- name: frontend
  image: node
  commands:
  - npm install
  - npm run test

...
